##  Chi squared test for all pathological features of 6 signatures
### Independency test of features

In [ ]:
# conda envrionment deepai

In [79]:
import os
import pandas as pd
import numpy as np
# install dependency for pd to read xlsx
# !conda install -c anaconda xlrd
from scipy.stats import chi2_contingency

### Path and load the gene signature list

In [96]:
path = "/media/visiopharm5/WDGold/deeplearning/MIL/CLAM/patch_reviewing"
signatures = []
for root, dirs, files in os.walk(path):
    for file in files:
        if file.endswith('.xlsx') and not file.startswith('_'):
            signatures.append(file[:-5])
print(signatures)

['6G_Interferon_Gamma', 'Gajewski_13G_Inflammatory', 'Inflammatory', 'Interferon_Gamma_Biology', 'Ribas_10G_Interferon_Gamma', 'T-cell_Exhaustion']

## Data pre-processing

In [97]:
for i in range(len(signatures)):
    # load patch reviewing data
    df = pd.read_excel(os.path.join(path, signatures[i]+'.xlsx'))
    # keep only patches in tp slides
    df = df.loc[df['class']=='tp']
    print(df.shape)
    display(df.head(3))
    
    # sum up counts of all features within a signature
    sumup = df.iloc[:, 4:].sum()
    
    if i == 0:
        # list features
        name_col = list(sumup.index)
        # df to summarize the feature counts in all signatures
        df_res = pd.DataFrame(columns = ['signature'] + name_col)
#         display(df_res)
    else:
        sumup = sumup[df_res.columns[1:]] # reorder the index
        assert list(sumup.index) == name_col                 
    
    df_res.loc[len(df_res)] = [signatures[i]] + list(sumup.values)

df_res.set_index('signature',inplace=True)
display(df_res)

(80, 27)

,Unnamed: 0,slide,patch,class,Tumor cells,vessels,blood,atypia,lymphocytes,neutrophils,...,Hyperchromasia,Macrotrabecular,Microtrabecular,Compact,Multinucleated cells,Pseudoglandular,necrosis,sarcomatoid,steatohepatitic,vascular spaces
0,79,HMNT0124_bis - 2017-06-05 05.08.39,HMNT0124_bis - 2017-06-05 05.08.39_-1_0.0_[273...,tp,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,78,HMNT0124_bis - 2017-06-05 05.08.39,HMNT0124_bis - 2017-06-05 05.08.39_-2_0.000150...,tp,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,77,HMNT0124_bis - 2017-06-05 05.08.39,HMNT0124_bis - 2017-06-05 05.08.39_-3_0.000300...,tp,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(144, 27)

,Unnamed: 0,slide,patch,class,Tumor cells,vessels,blood,atypia,lymphocytes,neutrophils,...,Hyperchromasia,Macrotrabecular,Microtrabecular,Compact,Multinucleated cells,Pseudoglandular,necrosis,sarcomatoid,steatohepatitic,vascular spaces
0,143,HMNT0124_bis - 2017-06-05 05.08.39,HMNT0124_bis - 2017-06-05 05.08.39_-1_0.0_[256...,tp,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,142,HMNT0124_bis - 2017-06-05 05.08.39,HMNT0124_bis - 2017-06-05 05.08.39_-2_0.000150...,tp,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,141,HMNT0124_bis - 2017-06-05 05.08.39,HMNT0124_bis - 2017-06-05 05.08.39_-3_0.000300...,tp,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(144, 27)

,Unnamed: 0,slide,patch,class,Tumor cells,vessels,blood,atypia,lymphocytes,neutrophils,...,Hyperchromasia,Macrotrabecular,Microtrabecular,Compact,Multinucleated cells,Pseudoglandular,necrosis,sarcomatoid,steatohepatitic,vascular spaces
0,143,HMNT0124_bis - 2017-06-05 05.08.39,HMNT0124_bis - 2017-06-05 05.08.39_-1_0.0_[133...,tp,1.0,NaN,NaN,1.0,1.0,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
1,142,HMNT0124_bis - 2017-06-05 05.08.39,HMNT0124_bis - 2017-06-05 05.08.39_-2_0.000150...,tp,1.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN
2,141,HMNT0124_bis - 2017-06-05 05.08.39,HMNT0124_bis - 2017-06-05 05.08.39_-3_0.000300...,tp,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN

(224, 27)

,Unnamed: 0,slide,patch,class,Tumor cells,vessels,blood,atypia,lymphocytes,neutrophils,...,Macrotrabecular,Microtrabecular,Compact,steatosis,Multinucleated cells,Pseudoglandular,necrosis,sarcomatoid,steatohepatitic,vascular spaces
0,223,HMNT0073_bis - 2017-06-17 22.30.07,HMNT0073_bis - 2017-06-17 22.30.07_-1_0.0_[153...,tp,1.0,1.0,1.0,NaN,NaN,NaN,...,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,222,HMNT0073_bis - 2017-06-17 22.30.07,HMNT0073_bis - 2017-06-17 22.30.07_-2_6.077180...,tp,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,221,HMNT0073_bis - 2017-06-17 22.30.07,HMNT0073_bis - 2017-06-17 22.30.07_-3_0.000121...,tp,1.0,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(64, 27)

,Unnamed: 0,slide,patch,class,Tumor cells,vessels,blood,atypia,lymphocytes,neutrophils,...,Hyperchromasia,Macrotrabecular,Microtrabecular,Compact,Multinucleated cells,Pseudoglandular,necrosis,sarcomatoid,steatohepatitic,vascular spaces
0,63,HMNT0185_bis - 2017-06-15 14.01.13,HMNT0185_bis - 2017-06-15 14.01.13_-1_0.0_[167...,tp,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,62,HMNT0185_bis - 2017-06-15 14.01.13,HMNT0185_bis - 2017-06-15 14.01.13_-2_0.000245...,tp,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,61,HMNT0185_bis - 2017-06-15 14.01.13,HMNT0185_bis - 2017-06-15 14.01.13_-3_0.000490...,tp,NaN,NaN,1.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

(256, 27)

,Unnamed: 0,slide,patch,class,Tumor cells,vessels,blood,atypia,lymphocytes,neutrophils,...,Hyperchromasia,Macrotrabecular,Microtrabecular,Compact,Multinucleated cells,Pseudoglandular,necrosis,sarcomatoid,steatohepatitic,vascular spaces
0,255,HMNT0124_bis - 2017-06-05 05.08.39,HMNT0124_bis - 2017-06-05 05.08.39_-1_0.0_[117...,tp,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,254,HMNT0124_bis - 2017-06-05 05.08.39,HMNT0124_bis - 2017-06-05 05.08.39_-2_0.000150...,tp,NaN,NaN,NaN,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,253,HMNT0124_bis - 2017-06-05 05.08.39,HMNT0124_bis - 2017-06-05 05.08.39_-3_0.000300...,tp,NaN,NaN,1.0,NaN,1.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

,Tumor cells,vessels,blood,atypia,lymphocytes,neutrophils,eosinophils,plasma cells,cholestasis,clear cells,...,Hyperchromasia,Macrotrabecular,Microtrabecular,Compact,Multinucleated cells,Pseudoglandular,necrosis,sarcomatoid,steatohepatitic,vascular spaces
signature,,,,,,,,,,,,,,,,,,,,,
6G_Interferon_Gamma,12.0,7.0,21.0,0.0,33.0,0.0,0.0,20.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Gajewski_13G_Inflammatory,22.0,4.0,5.0,0.0,74.0,5.0,0.0,16.0,0.0,0.0,...,0.0,0.0,7.0,12.0,6.0,0.0,0.0,0.0,0.0,0.0
Inflammatory,63.0,1.0,17.0,25.0,92.0,8.0,1.0,14.0,0.0,0.0,...,0.0,19.0,0.0,24.0,0.0,0.0,0.0,0.0,0.0,0.0
Interferon_Gamma_Biology,103.0,9.0,12.0,0.0,147.0,11.0,2.0,13.0,9.0,0.0,...,0.0,0.0,12.0,67.0,1.0,9.0,0.0,0.0,0.0,0.0
Ribas_10G_Interferon_Gamma,2.0,3.0,16.0,0.0,24.0,3.0,0.0,11.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
T-cell_Exhaustion,69.0,10.0,47.0,0.0,144.0,1.0,2.0,15.0,5.0,0.0,...,1.0,0.0,0.0,21.0,0.0,6.0,0.0,0.0,0.0,0.0

In [98]:
df_res.to_csv(os.path.join(path, 'summary.csv'), index=True)

## Chi squared test

In [108]:
# check variable independency by chi sqaured test, ValueError since there is 0
# chi2_contingency(observed=df_res)

In [100]:
# remove feautures (columns) containing values less than 5
df_res[df_res>=5].dropna(axis=1)

                            blood   lymphocytes  plasma cells
signature
6G_Interferon_Gamma           21.0         33.0          20.0
Gajewski_13G_Inflammatory      5.0         74.0          16.0
Inflammatory                  17.0         92.0          14.0
Interferon_Gamma_Biology      12.0        147.0          13.0
Ribas_10G_Interferon_Gamma    16.0         24.0          11.0
T-cell_Exhaustion             47.0        144.0          15.0

In [101]:
# Chi squared test after removing feautures containing values less than 5
chi2_contingency(df_res[df_res>=5].dropna(axis=1))

(78.5375540698413,
 9.70750898475515e-13,
 10,
 array([[ 12.110957  ,  52.75450763,   9.13453537],
        [ 15.54785021,  67.72538141,  11.72676838],
        [ 20.13037448,  87.68654646,  15.18307906],
        [ 28.14979196, 122.6185853 ,  21.23162275],
        [  8.34674064,  36.35783634,   6.29542302],
        [ 33.71428571, 146.85714286,  25.42857143]]))

### Change the less than 5 condition on expected table instead of observed table

In [102]:
# calculate expected table
expected =  np.outer(df_res.sum(axis=1),
                     df_res.sum()) / df_res.sum().sum()

expected = pd.DataFrame(expected)

expected.columns = df_res.columns
expected.index = df_res.index

display(expected)

,Tumor cells,vessels,blood,atypia,lymphocytes,neutrophils,eosinophils,plasma cells,cholestasis,clear cells,...,Hyperchromasia,Macrotrabecular,Microtrabecular,Compact,Multinucleated cells,Pseudoglandular,necrosis,sarcomatoid,steatohepatitic,vascular spaces
signature,,,,,,,,,,,,,,,,,,,,,
6G_Interferon_Gamma,18.561644,2.328767,8.082192,1.712329,35.205479,1.917808,0.342466,6.095890,0.958904,0.0,...,0.068493,1.301370,1.301370,8.493151,0.479452,1.027397,0.0,0.0,0.0,0.0
Gajewski_13G_Inflammatory,36.341745,4.559481,15.824081,3.352559,68.928623,3.754867,0.670512,11.935112,1.877433,0.0,...,0.134102,2.547945,2.547945,16.628695,0.938717,2.011536,0.0,0.0,0.0,0.0
Inflammatory,55.489546,6.961788,24.161500,5.118962,105.245854,5.733237,1.023792,18.223504,2.866619,0.0,...,0.204758,3.890411,3.890411,25.390050,1.433309,3.071377,0.0,0.0,0.0,0.0
Interferon_Gamma_Biology,81.475847,10.222062,35.476568,7.516222,154.533526,8.418169,1.503244,26.757751,4.209084,0.0,...,0.300649,5.712329,5.712329,37.280461,2.104542,4.509733,0.0,0.0,0.0,0.0
Ribas_10G_Interferon_Gamma,13.090844,1.642394,5.700072,1.207642,24.829128,1.352559,0.241528,4.299207,0.676280,0.0,...,0.048306,0.917808,0.917808,5.989906,0.338140,0.724585,0.0,0.0,0.0,0.0
T-cell_Exhaustion,66.040375,8.285508,28.755588,6.092286,125.257390,6.823360,1.218457,21.688536,3.411680,0.0,...,0.243691,4.630137,4.630137,30.217736,1.705840,3.655371,0.0,0.0,0.0,0.0

In [103]:
expected.to_csv(os.path.join(path, 'expected.csv'), index=True)

In [104]:
# remove feautures (columns) containing values less than 5
df_res[expected>=5].dropna(axis=1)

                            Tumor cells  blood   lymphocytes  Compact
signature
6G_Interferon_Gamma                12.0    21.0         33.0      0.0
Gajewski_13G_Inflammatory          22.0     5.0         74.0     12.0
Inflammatory                       63.0    17.0         92.0     24.0
Interferon_Gamma_Biology          103.0    12.0        147.0     67.0
Ribas_10G_Interferon_Gamma          2.0    16.0         24.0      0.0
T-cell_Exhaustion                  69.0    47.0        144.0     21.0

In [105]:
# Chi squared test after removing feautures containing values less than 5 on expected table 
chi2_contingency(df_res[expected>=5].dropna(axis=1))

(142.25892693064998,
 8.24178284070082e-23,
 15,
 array([[ 17.4157741 ,   7.58325219,  33.03213242,   7.96884129],
        [ 29.81791626,  12.98344693,  56.55501461,  13.6436222 ],
        [ 51.71957157,  22.51996105,  98.09542356,  23.66504382],
        [ 86.81499513,  37.80136319, 164.66017527,  39.72346641],
        [ 11.08276534,   4.82570594,  21.02044791,   5.07108082],
        [ 74.1489776 ,  32.28627069, 140.63680623,  33.92794547]]))