## Add the max, mean and std of test AUC to the summary.csv, only for tcga validation
#### For Mondor, we should use the best fold found in TCGA

In [1]:
import os
import numpy as np
import pandas as pd

In [32]:
root = "/media/visiopharm5/WDGold/deeplearning/MIL/CLAM/eval_results_349_tumor_masked"
target = "EVAL_tcga_hcc_tumor-masked_349_6G_Interferon_Gamma_cv_highvsrest_622_MIL_50_s1_cv"
path = os.path.join(root, target)

In [33]:
df_res = pd.read_csv(os.path.join(path, "summary.csv"), index_col=0)
display(df_res)
df_res.loc[len(df_res)] = ['best', df_res['test_auc'].max(), np.nan]
df_res.loc[len(df_res)] = ['mean', df_res.loc[:9, 'test_auc'].mean(), np.nan]
df_res.loc[len(df_res)] = ['std', df_res.loc[:9, 'test_auc'].std(), np.nan]
print(df_res.shape)
display(df_res)
df_res.to_csv(os.path.join(path, "summary.csv"))

   folds  test_auc  test_acc
0      0  0.610169  0.880597
1      1  0.758333  0.882353
2      2  0.667373  0.865672
3      3  0.646825  0.760563
4      4  0.508475  0.865672
5      5  0.614754  0.739130
6      6  0.682377  0.840580
7      7  0.500000  0.788732
8      8  0.656250  0.888889
9      9  0.652083  0.852941

(13, 3)

   folds  test_auc  test_acc
0      0  0.610169  0.880597
1      1  0.758333  0.882353
2      2  0.667373  0.865672
3      3  0.646825  0.760563
4      4  0.508475  0.865672
5      5  0.614754  0.739130
6      6  0.682377  0.840580
7      7  0.500000  0.788732
8      8  0.656250  0.888889
9      9  0.652083  0.852941
10  best  0.758333       NaN
11  mean  0.629664       NaN
12   std  0.077719       NaN